version: '3.8'

services:

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    ports: 
      - ${APP_PORT}:6379
    volumes:
      - ./redis.conf:/etc/redis.conf:ro
      - ${VOLUMES_PATH_PREFIX}/redis/data:/data/
    entrypoint: ["redis-server", "/etc/redis.conf"] 
    # entrypoint effect after run container immediately, cmd effect the last step of booting.
    # where can also use "command: /etc/redis.conf".
    restart: always

networks:
  default:
      name: ${APP_NETWORK}