version: '3.8'

services:

  redis:
    image: redis:${APP_REDIS_VERSION}
    container_name: ${APP_NAME}
    restart: always
    ports: 
      - ${APP_REDIS_PORT}:6379
    volumes:
      - ./src/redis.conf:/etc/redis.conf:ro
      - redis_data:/data
    entrypoint: ["redis-server", "/etc/redis.conf"] 
    restart: always

  services:
    redisinsight:
      image: redislabs/redisinsight::${APP_VERSION}
      ports:
      - "9001:8001"
      
networks:
  default:
      name: ${APP_NAME}

volumes:
  opencart:
  redis_data:
